/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    artigos: Artigo;
    branding: Branding;
    categorias: Categoria;
    contatos: Contato;
    cores: Core;
    depoimentos: Depoimento;
    empreendimentos: Empreendimento;
    links: Link;
    listas: Lista;
    paginas: Pagina;
    sedes: Sede;
    seo: Seo;
    textos: Texto;
    imagens: Imagen;
    usuarios: Usuario;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artigos".
 */
export interface Artigo {
  id: number;
  slug: string;
  publicado: string;
  autor: number | Usuario;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  conteudo: {
    titulo: string;
    resumo?: string | null;
    conteudo: string;
    imagemDestacada: number | Imagen;
    categorias: (number | Categoria)[];
  };
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  ogImage?: number | Imagen | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  name?: string | null;
  lastname?: string | null;
  thumbnail?: number | Imagen | null;
  roles: ('admin' | 'marketing')[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imagens".
 */
export interface Imagen {
  id: number;
  titulo: string;
  alt?: string | null;
  caption?: string | null;
  focal_x?: number | null;
  focal_y?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  categoria: string;
  updatedAt: string;
  createdAt: string;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: number;
  branding: string;
  imagens?:
    | {
        imagem?: number | Imagen | null;
        id?: string | null;
      }[]
    | null;
  fontes?:
    | {
        nome: string;
        referencia?: string | null;
        file?: number | null;
        headCode?: string | null;
        importCode?: string | null;
        classCode?: string | null;
        id?: string | null;
      }[]
    | null;
  cores?:
    | {
        cor?: (number | null) | Core;
        id?: string | null;
      }[]
    | null;
  tipografia?:
    | {
        tag?:
          | (
              | 'h1'
              | 'h2'
              | 'h3'
              | 'h4'
              | 'h5'
              | 'h6'
              | 'p'
              | 'a'
              | 'span'
              | 'div'
              | 'button'
              | 'label'
              | 'input'
              | 'select'
              | 'option'
            )
          | null;
        margin?: number | null;
        padding?: number | null;
        width?: number | null;
        height?: number | null;
        color?: (number | null) | Core;
        fontSize?: number | null;
        lineHeight?: number | null;
        fontStyle?: ('normal' | 'italic' | 'bold' | 'bolder') | null;
        textAlign?: ('left' | 'center' | 'right') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cores".
 */
export interface Core {
  id: number;
  nome: string;
  hex: string;
  referencia?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contatos".
 */
export interface Contato {
  id: number;
  tituloLista: string;
  subtitulo?: string | null;
  contatos?:
    | {
        nome: string;
        telefone?: string | null;
        email?: string | null;
        funcao?: string | null;
        diretoria?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "depoimentos".
 */
export interface Depoimento {
  id: number;
  imagem: number | Imagen;
  nome_cliente: string;
  empreendimento: string;
  depoimento: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empreendimentos".
 */
export interface Empreendimento {
  id: number;
  visualizacao?: ('venda' | 'portfolio' | 'rascunho') | null;
  empreendimento: string;
  slug: string;
  endereco: string;
  numero?: string | null;
  bairro: string;
  complemento?: string | null;
  cidade: string;
  estado: string;
  cep?: string | null;
  latitude: string;
  longitude: string;
  googleMaps: string;
  tipologia: string;
  area_comum: string;
  area_privativa: string;
  garagem: string;
  fase_obra?: ('pre-lancamento' | 'lancamento' | 'em-construcao' | 'pronto-pra-morar') | null;
  entrega?: string | null;
  valor_minimo?: number | null;
  valor_maximo?: number | null;
  percentual_vendido?: number | null;
  imagens?:
    | {
        referencia: string;
        imagem: number | Imagen;
        id?: string | null;
      }[]
    | null;
  textos?:
    | {
        referencia: string;
        texto: number | Texto;
        id?: string | null;
      }[]
    | null;

  cores?:
    | {
        referencia: string;
        cor: number | Core;
        id?: string | null;
      }[]
    | null;
  seo?: {
    seo?: (number | null) | Seo;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textos".
 */
export interface Texto {
  id: number;
  titulo: string;
  conteudo: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  referencia: string;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogTitle?: string | null;
  ogDescription?: string | null;
  ogImage?: number | Imagen | null;
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  scripts?:
    | {
        referencia: string;
        script: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  titulo: string;
  url: string;
  descricao?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listas".
 */
export interface Lista {
  id: number;
  tituloLista: string;
  subtitulo?: string | null;
  itens?:
    | {
        item: string;
        descricao?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paginas".
 */
export interface Pagina {
  id: number;
  pagina: string;
  textos?:
    | {
        referencia: string;
        texto: number | Texto;
        id?: string | null;
      }[]
    | null;
  imagens?:
    | {
        referencia: string;
        imagem: number | Imagen;
        id?: string | null;
      }[]
    | null;
  listas?:
    | {
        referencia: string;
        lista: number | Lista;
        id?: string | null;
      }[]
    | null;
  contatos?:
    | {
        referencia: string;
        contato: number | Contato;
        id?: string | null;
      }[]
    | null;
  depoimentos?:
    | {
        referencia: string;
        depoimento: number | Depoimento;
        id?: string | null;
      }[]
    | null;
  cores?:
    | {
        referencia: string;
        cor: number | Core;
        id?: string | null;
      }[]
    | null;

  links?:
    | {
        referencia: string;
        link: number | Link;
        id?: string | null;
      }[]
    | null;
  categorias?:
    | {
        referencia: string;
        categoria: number | Categoria;
        id?: string | null;
      }[]
    | null;
  seo?: {
    seo?: (number | null) | Seo;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sedes".
 */
export interface Sede {
  id: number;
  nome: string;
  endereco: string;
  numero?: string | null;
  bairro?: string | null;
  complemento?: string | null;
  cidade: string;
  estado: string;
  cep: string;
  googleMaps?: string | null;
  horario?: string | null;
  telefone?: string | null;
  email?: string | null;
  site?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  youtube?: string | null;
  twitter?: string | null;
  whatsapp?: string | null;
  telegram?: string | null;
  tiktok?: string | null;
  skype?: string | null;
  missao?: string | null;
  visao?: string | null;
  valores?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}

